@extends('layouts.app')
@section('title', 'İthalat')
@section('app-content')
<section class="workspace-hero"><div><p class="eyebrow">M16 / İthalat & Konteyner</p><h1>İthalat</h1><p>Konteyner, paket/komponent, malzeme konumu, mal kabul handoff ve landed-cost takibi.</p></div><div class="page-actions"><a class="button-primary" href="{{ route('import.report') }}">İthalat Raporu</a></div></section>
@if ($errors->any())<section class="notice-error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></section>@endif
@can('imports.manage')<section class="detail-card"><h2>Yeni İthalat Dosyası</h2><form method="POST" action="{{ route('import.store') }}" class="form-grid">@csrf
<div><label>Dosya No</label><input name="number" required maxlength="64"></div><div><label>Para Birimi</label><input name="currency_code" value="TRY" required maxlength="3"></div>
<div><label>Tedarikçi</label><select name="supplier_account_id"><option value="">Seçin</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->code }} — {{ $supplier->legal_name }}</option>@endforeach</select></div>
<div><label>Tedarikçi Ref.</label><input name="supplier_reference" maxlength="100"></div><div><label>Menşe</label><input name="origin_country" maxlength="100"></div><div><label>Yükleme Limanı</label><input name="loading_port" maxlength="150"></div><div><label>Varış Limanı</label><input name="destination_port" maxlength="150"></div><div><label>Çıkış Tarihi</label><input type="date" name="departure_date"></div><div><label>Tahmini Varış</label><input type="date" name="expected_arrival_date"></div><div style="grid-column:1/-1"><label>Not</label><textarea name="note" maxlength="2000"></textarea></div><div><button class="button-primary">Dosya Oluştur</button></div></form></section>@endcan
<section class="detail-card"><h2>İthalat Dosyaları</h2><div class="statement-table-card"><table class="data-table"><thead><tr><th>Dosya</th><th>Tedarikçi</th><th>Para</th><th>Durum</th><th>Tahmini Varış</th><th></th></tr></thead><tbody>@forelse($files as $file)<tr><td>{{ $file->number }}</td><td>{{ $file->supplier?->code }} {{ $file->supplier?->legal_name }}</td><td>{{ $file->currency_code }}</td><td>{{ $file->status }}</td><td>{{ $file->expected_arrival_date?->format('d.m.Y') }}</td><td><a href="{{ route('import.show',$file->id) }}">Aç</a></td></tr>@empty<tr><td colspan="6">İthalat dosyası yok.</td></tr>@endforelse</tbody></table></div>{{ $files->links() }}</section>
@endsection
