@extends('layouts.app')
@section('title', 'İthalat '.$file->number)
@section('app-content')
<section class="workspace-hero"><div><p class="eyebrow">M16 / İthalat Dosyası</p><h1>{{ $file->number }}</h1><p>{{ $file->status }} · {{ $file->currency_code }} · {{ $file->origin_country }} → {{ $file->destination_port }}</p></div><div class="page-actions"><a href="{{ route('import.picking-list',$file->id) }}">Toplama/Üretim Listesi</a><a href="{{ route('import.subcontract-list',$file->id) }}">Fason Toplama</a><a href="{{ route('import.loading-simulator',$file->id) }}">Yükleme Simülatörü</a></div></section>
@if(session('status'))<section class="notice-success">{{ session('status') }}</section>@endif @if($errors->any())<section class="notice-error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></section>@endif
<section class="detail-card"><h2>Yük Özeti</h2><p>{{ $loading['item_count'] }} kalem · {{ $loading['package_count'] }} paket · Brüt {{ $loading['gross_weight_kg'] }} kg · Net {{ $loading['net_weight_kg'] }} kg · {{ $loading['volume_m3'] }} m³</p></section>
@can('imports.manage')
<section class="detail-card"><h2>Lifecycle</h2><div class="page-actions">@if($file->status==='draft')<form method="POST" action="{{ route('import.in-transit',$file->id) }}">@csrf<button>Yola Çıkar</button></form>@endif @if($file->status==='in_transit')<form method="POST" action="{{ route('import.arrived',$file->id) }}">@csrf<input type="date" name="arrival_date"><button>Varışa Al</button></form>@endif @if(in_array($file->status,['arrived','receiving']))<form method="POST" action="{{ route('import.complete',$file->id) }}">@csrf<button>Tamamla</button></form>@endif</div></section>
@if(in_array($file->status,['draft','in_transit']))<section class="detail-card"><h2>Konteyner Ekle</h2><form method="POST" action="{{ route('import.containers.store',$file->id) }}" class="form-grid">@csrf<div><label>Konteyner No</label><input name="container_no" required></div><div><label>Mühür</label><input name="seal_no"></div><div><label>Tip</label><input name="container_type"></div><div><label>Azami kg</label><input name="max_weight_kg" type="number" step="0.000001"></div><div><label>Azami m³</label><input name="max_volume_m3" type="number" step="0.000001"></div><div><button>Konteyner Ekle</button></div></form></section>
<section class="detail-card"><h2>Kalem Ekle</h2><form method="POST" action="{{ route('import.items.store',$file->id) }}" class="form-grid">@csrf<div><label>Ürün</label><select name="product_id" required>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->code }} — {{ $product->name }}</option>@endforeach</select></div><div><label>Konteyner</label><select name="import_container_id"><option value="">Genel</option>@foreach($file->containers as $container)<option value="{{ $container->id }}">{{ $container->container_no }}</option>@endforeach</select></div><div><label>Miktar</label><input name="quantity" type="number" step="0.000001" required></div><div><label>Paket Ref.</label><input name="package_reference"></div><div><label>Komponent Ref.</label><input name="component_reference"></div><div><label>Paket Adedi</label><input name="package_count" type="number" min="0" value="0"></div><div><label>Brüt kg</label><input name="gross_weight_kg" type="number" step="0.000001" value="0"></div><div><label>Net kg</label><input name="net_weight_kg" type="number" step="0.000001" value="0"></div><div><label>Hacim m³</label><input name="volume_m3" type="number" step="0.000001" value="0"></div><div><label>Malzeme Konumu</label><input name="material_location"></div><div><label><input type="checkbox" name="subcontract_collection" value="1"> Fason toplama</label></div><div><button>Kalem Ekle</button></div></form></section>@endif
<section class="detail-card"><h2>Masraf Ekle</h2><form method="POST" action="{{ route('import.expenses.store',$file->id) }}" class="form-grid">@csrf<div><label>Kod</label><input name="expense_code" required></div><div><label>Açıklama</label><input name="description" required></div><div><label>Tutar</label><input name="amount" type="number" step="0.000001" required></div><div><label>Para</label><input name="currency_code" value="{{ $file->currency_code }}" required></div><div><label>Dağıtım</label><select name="allocation_basis"><option value="line_value">Satır Değeri</option><option value="quantity">Miktar</option></select></div><div><label><input type="checkbox" name="final" value="1"> Kesin masraf</label></div><div><button>Masraf Ekle</button></div></form></section>
@if(in_array($file->status,['arrived','receiving']))<section class="detail-card"><h2>Mal Kabul Handoff</h2><form method="POST" action="{{ route('import.receipt-links.store',$file->id) }}" class="form-grid">@csrf<div><label>İthalat Kalemi</label><select name="import_item_id">@foreach($file->items as $item)<option value="{{ $item->id }}">{{ $item->product?->code }} · {{ $item->quantity }}</option>@endforeach</select></div><div><label>Kesinleşmiş Mal Kabul Satırı</label><select name="goods_receipt_line_id">@foreach($receiptLines as $line)<option value="{{ $line->id }}">{{ $line->receipt_number }} · {{ $line->product_code }} · {{ $line->accepted_quantity }}</option>@endforeach</select></div><div><button>Bağla</button></div></form></section>
<section class="detail-card"><h2>Landed Cost</h2><form method="POST" action="{{ route('import.landed-cost',$file->id) }}" class="form-grid">@csrf<div><label>İşlem Anahtarı</label><input name="operation_key" required placeholder="LC-2026-001"></div><div><label>Dağıtım</label><select name="allocation_basis"><option value="line_value">Satır Değeri</option><option value="quantity">Miktar</option></select></div><div><button>Landed Cost Post Et</button></div></form></section>@endif
@endcan
<section class="detail-card"><h2>Konteynerler</h2><div class="statement-table-card"><table class="data-table"><thead><tr><th>No</th><th>Mühür</th><th>Tip</th><th>Azami kg</th><th>Azami m³</th></tr></thead><tbody>@foreach($file->containers as $container)<tr><td>{{ $container->container_no }}</td><td>{{ $container->seal_no }}</td><td>{{ $container->container_type }}</td><td>{{ $container->max_weight_kg }}</td><td>{{ $container->max_volume_m3 }}</td></tr>@endforeach</tbody></table></div></section>
<section class="detail-card"><h2>Kalemler</h2><div class="statement-table-card"><table class="data-table"><thead><tr><th>Ürün</th><th>Konteyner</th><th>Paket/Komponent</th><th>Miktar</th><th>Konum</th><th>Mal Kabul</th></tr></thead><tbody>@foreach($file->items as $item)<tr><td>{{ $item->product?->code }} — {{ $item->product?->name }}</td><td>{{ $item->container?->container_no }}</td><td>{{ $item->package_reference }} / {{ $item->component_reference }}</td><td>{{ $item->quantity }}</td><td>{{ $item->material_location }}</td><td>{{ $item->receiptLinks->sum('linked_quantity') }}</td></tr>@endforeach</tbody></table></div></section>
<section class="detail-card"><h2>Masraflar</h2><div class="statement-table-card"><table class="data-table"><thead><tr><th>Kod</th><th>Açıklama</th><th>Tutar</th><th>Durum</th><th>Dağıtım</th><th></th></tr></thead><tbody>@foreach($file->expenses as $expense)<tr><td>{{ $expense->expense_code }}</td><td>{{ $expense->description }}</td><td>{{ $expense->amount }} {{ $expense->currency_code }}</td><td>{{ $expense->status }}</td><td>{{ $expense->allocation_basis }}</td><td>@can('imports.manage')@if($expense->status==='provisional')<form method="POST" action="{{ route('import.expenses.finalize',[$file->id,$expense->id]) }}">@csrf<button>Kesinleştir</button></form>@endif@endcan</td></tr>@endforeach</tbody></table></div></section>
<section class="detail-card"><h2>Landed Cost Dağılımları</h2><div class="statement-table-card"><table class="data-table"><thead><tr><th>İşlem</th><th>Temel</th><th>Toplam</th><th>Dağıtılan</th></tr></thead><tbody>@foreach($costs as $cost)<tr><td>{{ $cost->operation_key }}</td><td>{{ $cost->allocation_basis }}</td><td>{{ $cost->expense_total }}</td><td>{{ $cost->allocated_amount }}</td></tr>@endforeach</tbody></table></div></section>
@endsection
