// <auto-generated />
using System;
using Mars.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mars.Infrastructure.Persistence.Migrations.Parties
{
    [DbContext(typeof(MarsDbContext))]
    [Migration("20260923233312_PartyImp006PartyMasterCompletion")]
    partial class PartyImp006PartyMasterCompletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mars.Infrastructure.Identity.MarsIdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Foundation.AuditEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EntityPublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_public_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_correlation");

                    b.HasIndex("ActorId", "OccurredAt")
                        .HasDatabaseName("ix_audit_actor_time");

                    b.HasIndex("EntityType", "EntityPublicId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entity_time");

                    b.ToTable("audit_events", "foundation");
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Foundation.IdempotencyOperationRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation_key");

                    b.Property<string>("RequestFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("ResultCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("result_code");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_operations");

                    b.HasIndex("Scope", "OperationKey")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_scope_key");

                    b.ToTable("idempotency_operations", "foundation", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_completed_state", "completed_at IS NULL OR status IN ('Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Foundation.OutboxMessageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AggregatePublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_public_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_token");

                    b.Property<DateTimeOffset?>("ClaimedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_until");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_error");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("PayloadSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("payload_schema_version");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_event_id");

                    b.HasIndex("State", "AvailableAt", "Id")
                        .HasDatabaseName("ix_outbox_pending_delivery");

                    b.ToTable("outbox_messages", "foundation", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_outbox_payload_schema_version", "payload_schema_version > 0");
                        });
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Foundation.PermissionGrantRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_actor_id");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("permission_code");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_actor_id");

                    b.HasKey("Id")
                        .HasName("pk_permission_grants");

                    b.HasIndex("ActorId", "CompanyId", "PermissionCode")
                        .IsUnique()
                        .HasDatabaseName("ux_permission_grant_actor_company_code");

                    b.HasIndex("CompanyId", "PermissionCode", "RevokedAt")
                        .HasDatabaseName("ix_permission_grant_company_code_state");

                    b.ToTable("permission_grants", "foundation", t =>
                        {
                            t.HasCheckConstraint("ck_permission_grant_code", "length(btrim(permission_code)) > 0 AND permission_code = btrim(permission_code)");

                            t.HasCheckConstraint("ck_permission_grant_revocation", "(revoked_at IS NULL AND revoked_by_actor_id IS NULL) OR revoked_at IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyAddressRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Line1")
                        .HasColumnType("text")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasColumnType("text")
                        .HasColumnName("line2");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("party_id");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("purpose");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_party_addresses");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_party_addresses_public_id");

                    b.HasIndex("PartyId", "CompanyId");

                    b.HasIndex("PartyId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("ux_party_addresses_active_default_purpose")
                        .HasFilter("\"state\" = 'Active' AND \"is_default\" = TRUE");

                    b.ToTable("addresses", "parties", t =>
                        {
                            t.HasCheckConstraint("ck_party_addresses_country", "length(btrim(country)) > 0 AND country = btrim(country)");

                            t.HasCheckConstraint("ck_party_addresses_purpose", "purpose IN ('Billing', 'Shipping', 'General')");

                            t.HasCheckConstraint("ck_party_addresses_state", "state IN ('Active', 'Inactive')");

                            t.HasCheckConstraint("ck_party_addresses_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyCommunicationPointRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_party_communication_points");

                    b.HasIndex("ContactId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_party_communication_points_public_id");

                    b.ToTable("communication_points", "parties", t =>
                        {
                            t.HasCheckConstraint("ck_party_communication_points_state", "state IN ('Active', 'Inactive')");

                            t.HasCheckConstraint("ck_party_communication_points_type", "length(btrim(type)) > 0 AND type = btrim(type)");

                            t.HasCheckConstraint("ck_party_communication_points_value", "length(btrim(value)) > 0 AND value = btrim(value)");

                            t.HasCheckConstraint("ck_party_communication_points_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyContactRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("party_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_party_contacts");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_party_contacts_public_id");

                    b.HasIndex("PartyId", "CompanyId");

                    b.ToTable("contacts", "parties", t =>
                        {
                            t.HasCheckConstraint("ck_party_contacts_name", "length(btrim(name)) > 0 AND name = btrim(name)");

                            t.HasCheckConstraint("ck_party_contacts_state", "state IN ('Active', 'Inactive')");

                            t.HasCheckConstraint("ck_party_contacts_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyExternalMappingRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_scope");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_identity");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("party_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_code");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_party_external_mappings");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_party_external_mappings_public_id");

                    b.HasIndex("PartyId", "CompanyId");

                    b.HasIndex("CompanyId", "SystemCode", "AccountScope", "ExternalIdentity")
                        .IsUnique()
                        .HasDatabaseName("ux_party_external_mappings_active_scope")
                        .HasFilter("\"state\" = 'Active'");

                    b.ToTable("external_mappings", "parties", t =>
                        {
                            t.HasCheckConstraint("ck_party_external_mappings_external_identity", "length(btrim(external_identity)) > 0 AND external_identity = btrim(external_identity)");

                            t.HasCheckConstraint("ck_party_external_mappings_state", "state IN ('Active', 'Inactive')");

                            t.HasCheckConstraint("ck_party_external_mappings_system", "length(btrim(system_code)) > 0 AND system_code = btrim(system_code)");

                            t.HasCheckConstraint("ck_party_external_mappings_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyMergeLineageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("SourcePartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_party_id");

                    b.Property<long>("SurvivorPartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("survivor_party_id");

                    b.HasKey("Id")
                        .HasName("pk_party_merge_lineage");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_party_merge_lineage_public_id");

                    b.HasIndex("SourcePartyId")
                        .IsUnique()
                        .HasDatabaseName("ux_party_merge_lineage_source");

                    b.HasIndex("SourcePartyId", "CompanyId");

                    b.HasIndex("SurvivorPartyId", "CompanyId");

                    b.ToTable("merge_lineage", "parties", t =>
                        {
                            t.HasCheckConstraint("ck_party_merge_lineage_distinct", "source_party_id <> survivor_party_id");

                            t.HasCheckConstraint("ck_party_merge_lineage_reason", "length(btrim(reason)) > 0 AND reason = btrim(reason)");
                        });
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<string>("PartyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("party_code");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.HasAlternateKey("Id", "CompanyId")
                        .HasName("ak_parties_id_company");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_parties_public_id");

                    b.HasIndex("CompanyId", "PartyCode")
                        .IsUnique()
                        .HasDatabaseName("ux_parties_company_code");

                    b.ToTable("parties", "parties", t =>
                        {
                            t.HasCheckConstraint("ck_parties_display_name", "display_name IS NULL OR (length(btrim(display_name)) > 0 AND display_name = btrim(display_name))");

                            t.HasCheckConstraint("ck_parties_kind", "kind IN ('Person', 'Organization')");

                            t.HasCheckConstraint("ck_parties_legal_name", "length(btrim(legal_name)) > 0 AND legal_name = btrim(legal_name)");

                            t.HasCheckConstraint("ck_parties_party_code", "length(btrim(party_code)) > 0 AND party_code = btrim(party_code)");

                            t.HasCheckConstraint("ck_parties_state", "state IN ('Active', 'Inactive', 'Merged')");

                            t.HasCheckConstraint("ck_parties_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyRoleRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("party_id");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role_type");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_party_roles");

                    b.HasIndex("PartyId", "RoleType")
                        .IsUnique()
                        .HasDatabaseName("ux_party_roles_party_role_type");

                    b.ToTable("party_roles", "parties", t =>
                        {
                            t.HasCheckConstraint("ck_party_roles_role_type", "role_type IN ('Customer', 'Supplier')");

                            t.HasCheckConstraint("ck_party_roles_state", "state IN ('Active', 'Inactive')");

                            t.HasCheckConstraint("ck_party_roles_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyTaxIdentityRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("jurisdiction");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("party_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scheme");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("value");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tax_identities");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_tax_identities_public_id");

                    b.HasIndex("PartyId", "CompanyId");

                    b.HasIndex("CompanyId", "Jurisdiction", "Scheme", "Value")
                        .IsUnique()
                        .HasDatabaseName("ux_tax_identities_active_company_identity")
                        .HasFilter("\"state\" = 'Active'");

                    b.ToTable("tax_identities", "parties", t =>
                        {
                            t.HasCheckConstraint("ck_tax_identities_jurisdiction", "jurisdiction = 'TR'");

                            t.HasCheckConstraint("ck_tax_identities_scheme", "scheme IN ('Vkn', 'Tckn')");

                            t.HasCheckConstraint("ck_tax_identities_state", "state IN ('Active', 'Inactive')");

                            t.HasCheckConstraint("ck_tax_identities_value", "(scheme = 'Vkn' AND value ~ '^[0-9]{10}$') OR (scheme = 'Tckn' AND value ~ '^[0-9]{11}$')");

                            t.HasCheckConstraint("ck_tax_identities_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", "identity");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", "identity");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", "identity");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", "identity");
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyAddressRecord", b =>
                {
                    b.HasOne("Mars.Infrastructure.Persistence.Parties.PartyRecord", null)
                        .WithMany()
                        .HasForeignKey("PartyId", "CompanyId")
                        .HasPrincipalKey("Id", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_addresses_party_company");
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyCommunicationPointRecord", b =>
                {
                    b.HasOne("Mars.Infrastructure.Persistence.Parties.PartyContactRecord", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_communication_points_contact");
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyContactRecord", b =>
                {
                    b.HasOne("Mars.Infrastructure.Persistence.Parties.PartyRecord", null)
                        .WithMany()
                        .HasForeignKey("PartyId", "CompanyId")
                        .HasPrincipalKey("Id", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_contacts_party_company");
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyExternalMappingRecord", b =>
                {
                    b.HasOne("Mars.Infrastructure.Persistence.Parties.PartyRecord", null)
                        .WithMany()
                        .HasForeignKey("PartyId", "CompanyId")
                        .HasPrincipalKey("Id", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_external_mappings_party_company");
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyMergeLineageRecord", b =>
                {
                    b.HasOne("Mars.Infrastructure.Persistence.Parties.PartyRecord", null)
                        .WithMany()
                        .HasForeignKey("SourcePartyId", "CompanyId")
                        .HasPrincipalKey("Id", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_merge_lineage_source_company");

                    b.HasOne("Mars.Infrastructure.Persistence.Parties.PartyRecord", null)
                        .WithMany()
                        .HasForeignKey("SurvivorPartyId", "CompanyId")
                        .HasPrincipalKey("Id", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_merge_lineage_survivor_company");
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyRoleRecord", b =>
                {
                    b.HasOne("Mars.Infrastructure.Persistence.Parties.PartyRecord", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_roles_party");
                });

            modelBuilder.Entity("Mars.Infrastructure.Persistence.Parties.PartyTaxIdentityRecord", b =>
                {
                    b.HasOne("Mars.Infrastructure.Persistence.Parties.PartyRecord", null)
                        .WithMany()
                        .HasForeignKey("PartyId", "CompanyId")
                        .HasPrincipalKey("Id", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tax_identities_party_company");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Mars.Infrastructure.Identity.MarsIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Mars.Infrastructure.Identity.MarsIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Mars.Infrastructure.Identity.MarsIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
