@extends('layouts.app')

@section('title', 'Fason '.$order->order_no)

@section('app-content')
<section class="workspace-hero"><div><p class="eyebrow">Fason Sipariş</p><h1>{{ $order->order_no }}</h1><p>{{ $order->supplier?->code }} — {{ $order->supplier?->legal_name }} · Mamul: {{ $order->outputProduct?->code }} — {{ $order->outputProduct?->name }}</p></div><div class="page-actions"><span class="status-badge">{{ $order->status }}</span><a href="{{ route('subcontract.index') }}">Fasona Dön</a></div></section>
@if($errors->any())<section class="notice-error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></section>@endif
<section class="detail-card"><h2>Custody Özeti</h2><div class="form-grid"><div><strong>Gönderilen Değer</strong><p>{{ number_format((float)$order->sent_value,2,',','.') }}</p></div><div><strong>Fire/Eksik Değeri</strong><p>{{ number_format((float)$order->loss_value,2,',','.') }}</p></div><div><strong>Alınan Mamul</strong><p>{{ $order->received_output_quantity }}</p></div><div><strong>Mamul Değeri</strong><p>{{ number_format((float)$order->received_output_value,2,',','.') }}</p></div></div></section>
@can('subcontract.manage')<section class="detail-card"><h2>Lifecycle</h2><div class="page-actions">@if($order->status==='draft')<form method="POST" action="{{ route('subcontract.send',$order->id) }}">@csrf<button class="button-primary">Malzemeleri Fasonda Gönder</button></form>@endif @if($order->status==='in_progress')<form method="POST" action="{{ route('subcontract.complete',$order->id) }}">@csrf<button class="button-primary">Reconcile ve Tamamla</button></form>@endif</div></section>@endcan
<section class="detail-card"><h2>Subcontract Custody</h2><div class="statement-table-card"><table class="data-table"><thead><tr><th>Malzeme</th><th>Gönderilen</th><th>Tüketilen</th><th>Fire/Eksik</th><th>Kalan</th><th>Gönderilen Değer</th><th>Tüketilen Değer</th><th>Kayıp Değer</th><th>Kalan Değer</th></tr></thead><tbody>@foreach($order->materials as $m)@php($rq=(float)$m->sent_quantity-(float)$m->consumed_quantity-(float)$m->loss_quantity)@php($rv=(float)$m->sent_value-(float)$m->consumed_value-(float)$m->loss_value)<tr><td>{{ $m->product?->code }} — {{ $m->product?->name }}</td><td>{{ $m->sent_quantity }}</td><td>{{ $m->consumed_quantity }}</td><td>{{ $m->loss_quantity }}</td><td>{{ number_format($rq,6,',','.') }}</td><td>{{ number_format((float)$m->sent_value,2,',','.') }}</td><td>{{ number_format((float)$m->consumed_value,2,',','.') }}</td><td>{{ number_format((float)$m->loss_value,2,',','.') }}</td><td>{{ number_format($rv,2,',','.') }}</td></tr>@endforeach</tbody></table></div></section>
@if($order->status==='in_progress')@can('subcontract.manage')
<section class="detail-card"><h2>Fire / Eksik</h2><form method="POST" action="{{ route('subcontract.losses.store',$order->id) }}" class="form-grid">@csrf<div><label>İşlem Anahtarı</label><input name="operation_key" value="loss-{{ $order->id }}-{{ now()->format('YmdHis') }}" required></div><div><label>Malzeme</label><select name="product_id" required>@foreach($order->materials as $m)<option value="{{ $m->product_id }}">{{ $m->product?->code }} — {{ $m->product?->name }}</option>@endforeach</select></div><div><label>Miktar</label><input name="quantity" type="number" min="0.000001" step="0.000001" required></div><div><label>Tür</label><select name="loss_type"><option value="fire">Fire</option><option value="missing">Eksik</option></select></div><div><label>Not</label><input name="note" maxlength="240"></div><div><button class="button-primary">Kaydet</button></div></form></section>
<section class="detail-card"><h2>Mamul Kabul</h2><form method="POST" action="{{ route('subcontract.receipts.store',$order->id) }}" class="form-grid">@csrf<div><label>İşlem Anahtarı</label><input name="operation_key" value="receipt-{{ $order->id }}-{{ now()->format('YmdHis') }}" required></div><div><label>Mamul Miktarı</label><input name="output_quantity" type="number" min="0.000001" step="0.000001" required></div>@foreach($order->materials as $i=>$m)<div><label>Tüketim: {{ $m->product?->code }}</label><input type="hidden" name="consumption[{{ $i }}][product_id]" value="{{ $m->product_id }}"><input name="consumption[{{ $i }}][quantity]" type="number" min="0.000001" step="0.000001" placeholder="Kalan custody"></div>@endforeach<div><button class="button-primary">Mamul Kabul Et</button></div></form></section>
@endcan @endif
<section class="detail-card"><h2>Teknik / Fotoğraf / Talimat Dosyaları</h2>@can('subcontract.manage')<form method="POST" enctype="multipart/form-data" action="{{ route('subcontract.files.store',$order->id) }}" class="form-grid">@csrf<div><label>Etiket</label><input name="label" maxlength="160" placeholder="Teknik resim, fotoğraf, iş talimatı..."></div><div><label>Dosya</label><input type="file" name="file" required></div><div><button class="button-primary">Yükle</button></div></form>@endcan<div class="statement-table-card"><table class="data-table"><thead><tr><th>Etiket</th><th>Dosya</th><th>SHA-256</th><th>Durum</th><th></th></tr></thead><tbody>@forelse($attachments as $a)<tr><td>{{ $a->label??'—' }}</td><td>{{ $a->fileAsset?->original_name }}</td><td><code>{{ $a->fileAsset?->sha256 }}</code></td><td>{{ $a->detached_at?'Arşiv':'Aktif' }}</td><td>@if(!$a->detached_at)<a href="{{ route('subcontract.files.download',[$order->id,$a->id]) }}">İndir</a>@can('subcontract.manage') <form method="POST" action="{{ route('subcontract.files.detach',[$order->id,$a->id]) }}" style="display:inline">@csrf<button class="button-link">Arşivle</button></form>@endcan @endif</td></tr>@empty<tr><td colspan="5">Dosya yok.</td></tr>@endforelse</tbody></table></div></section>
<section class="detail-card"><h2>Mamul Kabulleri</h2><div class="statement-table-card"><table class="data-table"><thead><tr><th>Tarih</th><th>Miktar</th><th>Taşıma Değeri</th><th>Operation</th></tr></thead><tbody>@forelse($order->receipts as $r)<tr><td>{{ $r->occurred_at }}</td><td>{{ $r->output_quantity }}</td><td>{{ number_format((float)$r->carrying_value,2,',','.') }}</td><td><code>{{ $r->operation_key }}</code></td></tr>@empty<tr><td colspan="4">Kabul yok.</td></tr>@endforelse</tbody></table></div></section>
<section class="detail-card"><h2>Lifecycle Olayları</h2><div class="statement-table-card"><table class="data-table"><thead><tr><th>Tarih</th><th>Olay</th><th>Payload</th></tr></thead><tbody>@foreach($order->events->sortBy('id') as $e)<tr><td>{{ $e->occurred_at }}</td><td>{{ $e->event_type }}</td><td><code>{{ json_encode($e->payload,JSON_UNESCAPED_UNICODE) }}</code></td></tr>@endforeach</tbody></table></div></section>
@endsection
