<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Mars.Application/Mars.Application.csproj" />
    <ProjectReference Include="../../src/Mars.Infrastructure/Mars.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Mars.Worker/Mars.Worker.csproj" />
    <ProjectReference Include="../../src/Mars.Api/Mars.Api.csproj" />
  </ItemGroup>
</Project>
