<?php

namespace App\Modules\Reports;

use Illuminate\Database\Query\Builder;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;

final class OperationalReportCatalog
{
    /** @return array<string, array{category:string,title:string,source:string}> */
    public function definitions(): array
    {
        return [
            'ACC-01' => ['category' => 'account_finance', 'title' => 'Hesap ekstresi', 'source' => 'account_transactions'],
            'ACC-02' => ['category' => 'account_finance', 'title' => 'Hesap hareketi detay', 'source' => 'account_transactions'],
            'ACC-03' => ['category' => 'account_finance', 'title' => 'Cari yaşlandırma', 'source' => 'account_transactions + accounts.due_days'],
            'ACC-04' => ['category' => 'account_finance', 'title' => 'Tahsilat / ödeme performansı', 'source' => 'account_transactions'],
            'ACC-05' => ['category' => 'account_finance', 'title' => 'Risk / maruziyet ve limit aşımı', 'source' => 'account_transactions + accounts.risk_limit'],
            'SAL-01' => ['category' => 'sales', 'title' => 'Satış sipariş durumu', 'source' => 'sales_orders'],
            'SAL-02' => ['category' => 'sales', 'title' => 'Sevkiyat performansı', 'source' => 'dispatches + dispatch_lines'],
            'SAL-03' => ['category' => 'sales', 'title' => 'Fatura ve iade', 'source' => 'sales_invoices + sales_returns'],
            'SAL-04' => ['category' => 'sales', 'title' => 'Müşteri bazlı satış', 'source' => 'finalized sales_invoices'],
            'SAL-05' => ['category' => 'sales', 'title' => 'Ürün bazlı satış', 'source' => 'finalized sales_invoice_lines'],
            'PUR-01' => ['category' => 'purchase', 'title' => 'Satınalma sipariş durumu', 'source' => 'purchase_orders'],
            'PUR-02' => ['category' => 'purchase', 'title' => 'Tedarikçi performansı', 'source' => 'purchase_orders + goods_receipts'],
            'PUR-03' => ['category' => 'purchase', 'title' => 'Mal kabul', 'source' => 'goods_receipts + goods_receipt_lines'],
            'PUR-04' => ['category' => 'purchase', 'title' => 'Alım faturaları', 'source' => 'supplier_invoices'],
            'PUR-05' => ['category' => 'purchase', 'title' => 'Bekleyen / red kalite miktarı', 'source' => 'goods_receipt_lines custody'],
            'STK-01' => ['category' => 'stock_logistics', 'title' => 'Stok bakiye ve kullanılabilir', 'source' => 'stock_balances availability projection'],
            'STK-02' => ['category' => 'stock_logistics', 'title' => 'Stok hareketi', 'source' => 'stock_movements append-only ledger'],
            'STK-03' => ['category' => 'stock_logistics', 'title' => 'Lot / seri izlenebilirlik', 'source' => 'stock_movements immutable source lineage'],
            'STK-04' => ['category' => 'stock_logistics', 'title' => 'Depolar arası transfer', 'source' => 'warehouse_transfers + warehouse_transfer_lines'],
            'STK-05' => ['category' => 'stock_logistics', 'title' => 'Sayım farkı', 'source' => 'stock_counts + stock_count_lines variance projection'],
            'PRD-01' => ['category' => 'production_subcontract', 'title' => 'Üretim emri durumları', 'source' => 'production_orders'],
            'PRD-02' => ['category' => 'production_subcontract', 'title' => 'Üretim tüketim ve fire', 'source' => 'production_order_materials + production_losses'],
            'PRD-03' => ['category' => 'production_subcontract', 'title' => 'Çıktı verimliliği', 'source' => 'production_orders'],
            'PRD-04' => ['category' => 'production_subcontract', 'title' => 'Fason custody bakiyesi', 'source' => 'subcontract_order_materials'],
            'PRD-05' => ['category' => 'production_subcontract', 'title' => 'Fason tüketim / kayıp / iade farkı', 'source' => 'subcontract_order_materials + subcontract_orders'],
            'IMP-01' => ['category' => 'import_commerce', 'title' => 'İthalat dosyası maliyet özeti', 'source' => 'import_files + import_expenses'],
            'IMP-02' => ['category' => 'import_commerce', 'title' => 'Landed-cost dağıtımı', 'source' => 'import_landed_cost_batches + allocations'],
            'IMP-03' => ['category' => 'import_commerce', 'title' => 'Kur farkı / provisional-posting etkisi', 'source' => 'import_expenses provisional/final evidence'],
            'IMP-04' => ['category' => 'import_commerce', 'title' => 'Marketplace order / claim / settlement', 'source' => 'channel_order_inbox + channel_return_events'],
            'IMP-05' => ['category' => 'import_commerce', 'title' => 'Marketplace clearing reconciliation', 'source' => 'channel_settlement_evidence'],
            'AUT-01' => ['category' => 'automation_integration', 'title' => 'Kural çalıştırma başarı / hata', 'source' => 'automation_runs'],
            'AUT-02' => ['category' => 'automation_integration', 'title' => 'Bekleyen / stale / recovering runlar', 'source' => 'automation_runs lifecycle'],
            'AUT-03' => ['category' => 'automation_integration', 'title' => 'Notification delivery durumu', 'source' => 'notification_deliveries'],
            'AUT-04' => ['category' => 'automation_integration', 'title' => 'Integration call durumu', 'source' => 'integration_events + integration_sync_effects'],
            'AUT-05' => ['category' => 'automation_integration', 'title' => 'Dead-letter / operator-action required', 'source' => 'channel_problems + failed integration events'],
            'MGT-01' => ['category' => 'management', 'title' => 'Günlük satış özeti', 'source' => 'finalized sales_invoices'],
            'MGT-02' => ['category' => 'management', 'title' => 'Tahsilat / ödeme özeti', 'source' => 'account_transactions'],
            'MGT-03' => ['category' => 'management', 'title' => 'Stok ve kritik stok özeti', 'source' => 'stock_balances availability projection'],
            'MGT-04' => ['category' => 'management', 'title' => 'Operasyon / entegrasyon istisna özeti', 'source' => 'channel_problems + operations_metrics'],
            'MGT-05' => ['category' => 'management', 'title' => 'Kârlılık görünümü — yalnız settled/recognized veri', 'source' => 'finalized sales_invoice_lines + invoice_out ledger cost'],
        ];
    }

    /** @return list<string> */
    public function keys(): array
    {
        return array_keys($this->definitions());
    }

    public function query(string $reportKey, int $companyId): Builder
    {
        if (! isset($this->definitions()[$reportKey])) {
            throw new InvalidArgumentException('Unknown report key: '.$reportKey);
        }

        return match ($reportKey) {
            'ACC-01' => DB::table('account_transactions as tx')->join('accounts as account', fn ($join) => $join->on('account.company_id', '=', 'tx.company_id')->on('account.id', '=', 'tx.account_id'))->where('tx.company_id', $companyId)->select(['tx.posting_date', 'account.code as account_code', 'account.legal_name', 'tx.currency_code', 'tx.signed_amount', 'tx.memo'])->orderByDesc('tx.posting_date')->orderByDesc('tx.id'),
            'ACC-02' => DB::table('account_transactions as tx')->join('accounts as account', fn ($join) => $join->on('account.company_id', '=', 'tx.company_id')->on('account.id', '=', 'tx.account_id'))->where('tx.company_id', $companyId)->select(['tx.posting_date', 'account.code as account_code', 'tx.source_type', 'tx.source_id', 'tx.effect_type', 'tx.signed_amount', 'tx.currency_code'])->orderByDesc('tx.posting_date')->orderByDesc('tx.id'),
            'ACC-03' => DB::table('accounts as account')->leftJoin('account_transactions as tx', fn ($join) => $join->on('tx.company_id', '=', 'account.company_id')->on('tx.account_id', '=', 'account.id'))->where('account.company_id', $companyId)->groupBy('account.id', 'account.code', 'account.legal_name', 'account.book_currency_code', 'account.due_days')->select(['account.code', 'account.legal_name', 'account.book_currency_code', 'account.due_days'])->selectRaw('COALESCE(SUM(tx.signed_amount), 0) AS outstanding')->selectRaw("COALESCE(SUM(CASE WHEN tx.signed_amount > 0 AND tx.posting_date + account.due_days < CURRENT_DATE THEN tx.signed_amount ELSE 0 END), 0) AS overdue_exposure")->orderBy('account.code'),
            'ACC-04' => DB::table('account_transactions as tx')->join('accounts as account', fn ($join) => $join->on('account.company_id', '=', 'tx.company_id')->on('account.id', '=', 'tx.account_id'))->where('tx.company_id', $companyId)->groupBy('account.id', 'account.code', 'account.legal_name', 'tx.currency_code')->select(['account.code', 'account.legal_name', 'tx.currency_code'])->selectRaw('COALESCE(SUM(CASE WHEN tx.signed_amount > 0 THEN tx.signed_amount ELSE 0 END), 0) AS positive_postings')->selectRaw('COALESCE(ABS(SUM(CASE WHEN tx.signed_amount < 0 THEN tx.signed_amount ELSE 0 END)), 0) AS settlements')->orderBy('account.code'),
            'ACC-05' => DB::table('accounts as account')->leftJoin('account_transactions as tx', fn ($join) => $join->on('tx.company_id', '=', 'account.company_id')->on('tx.account_id', '=', 'account.id'))->where('account.company_id', $companyId)->groupBy('account.id', 'account.code', 'account.legal_name', 'account.book_currency_code', 'account.risk_limit')->select(['account.code', 'account.legal_name', 'account.book_currency_code', 'account.risk_limit'])->selectRaw('COALESCE(SUM(tx.signed_amount), 0) AS exposure')->selectRaw('GREATEST(COALESCE(SUM(tx.signed_amount), 0) - account.risk_limit, 0) AS limit_excess')->orderByDesc('limit_excess'),
            'SAL-01' => DB::table('sales_orders')->where('company_id', $companyId)->select(['number', 'order_date', 'status', 'account_id', 'currency_code', 'gross_total'])->orderByDesc('order_date')->orderByDesc('id'),
            'SAL-02' => DB::table('dispatches as dispatch')->leftJoin('dispatch_lines as line', fn ($join) => $join->on('line.company_id', '=', 'dispatch.company_id')->on('line.dispatch_id', '=', 'dispatch.id'))->where('dispatch.company_id', $companyId)->groupBy('dispatch.id', 'dispatch.number', 'dispatch.dispatch_date', 'dispatch.status', 'dispatch.carrier_name')->select(['dispatch.number', 'dispatch.dispatch_date', 'dispatch.status', 'dispatch.carrier_name'])->selectRaw('COALESCE(SUM(line.quantity), 0) AS dispatched_quantity')->orderByDesc('dispatch.dispatch_date'),
            'SAL-03' => DB::table('sales_invoices as invoice')->leftJoin('sales_returns as return', fn ($join) => $join->on('return.company_id', '=', 'invoice.company_id')->on('return.sales_invoice_id', '=', 'invoice.id'))->where('invoice.company_id', $companyId)->groupBy('invoice.id', 'invoice.number', 'invoice.invoice_date', 'invoice.status', 'invoice.currency_code', 'invoice.gross_total')->select(['invoice.number', 'invoice.invoice_date', 'invoice.status', 'invoice.currency_code', 'invoice.gross_total'])->selectRaw('COALESCE(SUM(return.credited_gross_total), 0) AS credited_return_total')->orderByDesc('invoice.invoice_date'),
            'SAL-04' => DB::table('sales_invoices as invoice')->join('accounts as account', fn ($join) => $join->on('account.company_id', '=', 'invoice.company_id')->on('account.id', '=', 'invoice.account_id'))->where('invoice.company_id', $companyId)->where('invoice.status', 'finalized')->groupBy('account.id', 'account.code', 'account.legal_name', 'invoice.currency_code')->select(['account.code', 'account.legal_name', 'invoice.currency_code'])->selectRaw('COUNT(*) AS invoice_count')->selectRaw('SUM(invoice.net_total) AS net_sales')->selectRaw('SUM(invoice.gross_total) AS gross_sales')->orderByDesc('gross_sales'),
            'SAL-05' => DB::table('sales_invoice_lines as line')->join('sales_invoices as invoice', fn ($join) => $join->on('invoice.company_id', '=', 'line.company_id')->on('invoice.id', '=', 'line.sales_invoice_id'))->where('line.company_id', $companyId)->where('invoice.status', 'finalized')->groupBy('line.product_id', 'line.product_code', 'line.product_name', 'invoice.currency_code')->select(['line.product_id', 'line.product_code', 'line.product_name', 'invoice.currency_code'])->selectRaw('SUM(line.quantity) AS quantity')->selectRaw('SUM(line.net_total) AS net_sales')->selectRaw('SUM(line.gross_total) AS gross_sales')->orderByDesc('net_sales'),
            'PUR-01' => DB::table('purchase_orders')->where('company_id', $companyId)->select(['number', 'order_date', 'status', 'account_id', 'currency_code', 'gross_total'])->orderByDesc('order_date')->orderByDesc('id'),
            'PUR-02' => DB::table('purchase_orders as purchase')->join('accounts as account', fn ($join) => $join->on('account.company_id', '=', 'purchase.company_id')->on('account.id', '=', 'purchase.account_id'))->leftJoin('goods_receipts as receipt', fn ($join) => $join->on('receipt.company_id', '=', 'purchase.company_id')->on('receipt.purchase_order_id', '=', 'purchase.id'))->where('purchase.company_id', $companyId)->groupBy('account.id', 'account.code', 'account.legal_name')->select(['account.code', 'account.legal_name'])->selectRaw("COUNT(DISTINCT purchase.id) AS order_count")->selectRaw("COUNT(DISTINCT CASE WHEN receipt.status = 'finalized' THEN receipt.id END) AS finalized_receipt_count")->orderBy('account.code'),
            'PUR-03' => DB::table('goods_receipts as receipt')->leftJoin('goods_receipt_lines as line', fn ($join) => $join->on('line.company_id', '=', 'receipt.company_id')->on('line.goods_receipt_id', '=', 'receipt.id'))->where('receipt.company_id', $companyId)->groupBy('receipt.id', 'receipt.number', 'receipt.receipt_date', 'receipt.status')->select(['receipt.number', 'receipt.receipt_date', 'receipt.status'])->selectRaw('COALESCE(SUM(line.received_quantity), 0) AS received_quantity')->selectRaw('COALESCE(SUM(line.accepted_quantity), 0) AS accepted_quantity')->orderByDesc('receipt.receipt_date'),
            'PUR-04' => DB::table('supplier_invoices')->where('company_id', $companyId)->select(['number', 'invoice_date', 'status', 'account_id', 'currency_code', 'net_total', 'tax_total', 'gross_total'])->orderByDesc('invoice_date')->orderByDesc('id'),
            'PUR-05' => DB::table('goods_receipt_lines as line')->join('goods_receipts as receipt', fn ($join) => $join->on('receipt.company_id', '=', 'line.company_id')->on('receipt.id', '=', 'line.goods_receipt_id'))->where('line.company_id', $companyId)->groupBy('line.product_id', 'line.product_code', 'line.product_name')->select(['line.product_id', 'line.product_code', 'line.product_name'])->selectRaw('SUM(line.pending_quantity) AS pending_quantity')->selectRaw('SUM(line.rejected_quantity) AS rejected_quantity')->orderByDesc('pending_quantity'),
            'STK-01' => DB::table('stock_balances as balance')->join('products as product', fn ($join) => $join->on('product.company_id', '=', 'balance.company_id')->on('product.id', '=', 'balance.product_id'))->join('warehouses as warehouse', fn ($join) => $join->on('warehouse.company_id', '=', 'balance.company_id')->on('warehouse.id', '=', 'balance.warehouse_id'))->where('balance.company_id', $companyId)->select(['product.code as product_code', 'product.name as product_name', 'warehouse.code as warehouse_code', 'balance.quantity', 'balance.reserved_quantity', 'balance.blocked_quantity', 'balance.available_quantity', 'balance.inventory_value'])->orderBy('product.code'),
            'STK-02' => DB::table('stock_movements as movement')->join('products as product', fn ($join) => $join->on('product.company_id', '=', 'movement.company_id')->on('product.id', '=', 'movement.product_id'))->where('movement.company_id', $companyId)->select(['movement.occurred_at', 'product.code as product_code', 'movement.movement_type', 'movement.quantity_delta', 'movement.unit_cost', 'movement.value_delta', 'movement.source_type', 'movement.source_id', 'movement.effect_type'])->orderByDesc('movement.occurred_at')->orderByDesc('movement.id'),
            'STK-03' => DB::table('stock_movements as movement')->join('products as product', fn ($join) => $join->on('product.company_id', '=', 'movement.company_id')->on('product.id', '=', 'movement.product_id'))->where('movement.company_id', $companyId)->select(['movement.occurred_at', 'product.code as product_code', 'product.name as product_name', 'movement.operation_key', 'movement.source_type', 'movement.source_id', 'movement.effect_type', 'movement.movement_type', 'movement.quantity_delta'])->orderByDesc('movement.occurred_at')->orderByDesc('movement.id'),
            'STK-04' => DB::table('warehouse_transfers as transfer')->leftJoin('warehouse_transfer_lines as line', fn ($join) => $join->on('line.company_id', '=', 'transfer.company_id')->on('line.transfer_id', '=', 'transfer.id'))->where('transfer.company_id', $companyId)->groupBy('transfer.id', 'transfer.status', 'transfer.source_warehouse_id', 'transfer.destination_warehouse_id', 'transfer.issued_at', 'transfer.completed_at')->select(['transfer.status', 'transfer.source_warehouse_id', 'transfer.destination_warehouse_id', 'transfer.issued_at', 'transfer.completed_at'])->selectRaw('COALESCE(SUM(line.in_transit_quantity), 0) AS in_transit_quantity')->selectRaw('COALESCE(SUM(line.in_transit_value), 0) AS in_transit_value')->orderByDesc('transfer.issued_at'),
            'STK-05' => DB::table('stock_count_lines as line')->join('stock_counts as count', fn ($join) => $join->on('count.company_id', '=', 'line.company_id')->on('count.id', '=', 'line.stock_count_id'))->join('products as product', fn ($join) => $join->on('product.company_id', '=', 'line.company_id')->on('product.id', '=', 'line.product_id'))->where('line.company_id', $companyId)->select(['count.started_at', 'count.status', 'product.code as product_code', 'line.expected_quantity', 'line.counted_quantity', 'line.variance_quantity'])->orderByDesc('count.started_at'),
            'PRD-01' => DB::table('production_orders')->where('company_id', $companyId)->select(['order_no', 'status', 'product_id', 'planned_quantity', 'output_quantity', 'material_cost', 'loss_cost', 'output_value', 'completed_at'])->orderByDesc('id'),
            'PRD-02' => DB::table('production_orders as production')->leftJoin('production_order_materials as material', fn ($join) => $join->on('material.company_id', '=', 'production.company_id')->on('material.production_order_id', '=', 'production.id'))->where('production.company_id', $companyId)->groupBy('production.id', 'production.order_no', 'production.status', 'production.loss_cost')->select(['production.order_no', 'production.status', 'production.loss_cost'])->selectRaw('COALESCE(SUM(material.issued_quantity), 0) AS issued_material_quantity')->selectRaw('COALESCE(SUM(material.issued_value), 0) AS issued_material_value')->orderByDesc('production.id'),
            'PRD-03' => DB::table('production_orders')->where('company_id', $companyId)->select(['order_no', 'status', 'planned_quantity', 'output_quantity', 'output_unit_cost', 'output_value'])->selectRaw('CASE WHEN planned_quantity = 0 THEN 0 ELSE output_quantity / planned_quantity END AS output_efficiency')->orderByDesc('id'),
            'PRD-04' => DB::table('subcontract_order_materials as material')->join('subcontract_orders as subcontract', fn ($join) => $join->on('subcontract.company_id', '=', 'material.company_id')->on('subcontract.id', '=', 'material.subcontract_order_id'))->where('material.company_id', $companyId)->select(['subcontract.order_no', 'material.product_id', 'material.sent_quantity', 'material.consumed_quantity', 'material.loss_quantity'])->selectRaw('material.sent_quantity - material.consumed_quantity - material.loss_quantity AS custody_quantity')->orderByDesc('subcontract.id'),
            'PRD-05' => DB::table('subcontract_orders as subcontract')->leftJoin('subcontract_order_materials as material', fn ($join) => $join->on('material.company_id', '=', 'subcontract.company_id')->on('material.subcontract_order_id', '=', 'subcontract.id'))->where('subcontract.company_id', $companyId)->groupBy('subcontract.id', 'subcontract.order_no', 'subcontract.status', 'subcontract.received_output_quantity', 'subcontract.received_output_value', 'subcontract.loss_value')->select(['subcontract.order_no', 'subcontract.status', 'subcontract.received_output_quantity', 'subcontract.received_output_value', 'subcontract.loss_value'])->selectRaw('COALESCE(SUM(material.sent_quantity), 0) AS sent_quantity')->selectRaw('COALESCE(SUM(material.consumed_quantity), 0) AS consumed_quantity')->selectRaw('COALESCE(SUM(material.loss_quantity), 0) AS loss_quantity')->orderByDesc('subcontract.id'),
            'IMP-01' => DB::table('import_files as import')->leftJoin('import_expenses as expense', fn ($join) => $join->on('expense.company_id', '=', 'import.company_id')->on('expense.import_file_id', '=', 'import.id'))->where('import.company_id', $companyId)->groupBy('import.id', 'import.number', 'import.status', 'import.currency_code')->select(['import.number', 'import.status', 'import.currency_code'])->selectRaw('COALESCE(SUM(expense.amount), 0) AS expense_total')->selectRaw("COALESCE(SUM(CASE WHEN expense.status = 'provisional' THEN expense.amount ELSE 0 END), 0) AS provisional_expense_total")->orderByDesc('import.id'),
            'IMP-02' => DB::table('import_landed_cost_batches as batch')->leftJoin('import_landed_cost_allocations as allocation', fn ($join) => $join->on('allocation.company_id', '=', 'batch.company_id')->on('allocation.landed_cost_batch_id', '=', 'batch.id'))->where('batch.company_id', $companyId)->groupBy('batch.id', 'batch.import_file_id', 'batch.allocation_basis', 'batch.expense_total', 'batch.currency_code', 'batch.posted_at')->select(['batch.import_file_id', 'batch.allocation_basis', 'batch.expense_total', 'batch.currency_code', 'batch.posted_at'])->selectRaw('COALESCE(SUM(allocation.allocated_amount), 0) AS allocated_total')->selectRaw('batch.expense_total - COALESCE(SUM(allocation.allocated_amount), 0) AS reconciliation_difference')->orderByDesc('batch.posted_at'),
            'IMP-03' => DB::table('import_expenses')->where('company_id', $companyId)->groupBy('currency_code', 'status')->select(['currency_code', 'status'])->selectRaw('COUNT(*) AS expense_count')->selectRaw('SUM(amount) AS amount')->orderBy('currency_code')->orderBy('status'),
            'IMP-04' => DB::table('channel_order_inbox')->where('company_id', $companyId)->groupBy('connection_id', 'status', 'financial_mode')->select(['connection_id', 'status', 'financial_mode'])->selectRaw('COUNT(*) AS order_count')->selectRaw('MAX(received_at) AS last_received_at')->orderByDesc('last_received_at'),
            'IMP-05' => DB::table('channel_settlement_evidence')->where('company_id', $companyId)->groupBy('connection_id', 'currency_code', 'clearing_account_id', 'status')->select(['connection_id', 'currency_code', 'clearing_account_id', 'status'])->selectRaw('SUM(gross_amount) AS gross_amount')->selectRaw('SUM(fee_amount) AS fee_amount')->selectRaw('SUM(net_amount) AS net_amount')->selectRaw("SUM(CASE WHEN status = 'handed_off' THEN net_amount ELSE 0 END) AS handed_off_net")->orderBy('connection_id'),
            'AUT-01' => DB::table('automation_runs')->where('company_id', $companyId)->groupBy('status')->select(['status'])->selectRaw('COUNT(*) AS run_count')->selectRaw('MAX(created_at) AS last_created_at')->orderBy('status'),
            'AUT-02' => DB::table('automation_runs')->where('company_id', $companyId)->select(['id', 'rule_id', 'trigger_key', 'status', 'started_at', 'finished_at', 'created_at'])->whereNull('finished_at')->orderBy('created_at'),
            'AUT-03' => DB::table('notification_deliveries')->where('company_id', $companyId)->groupBy('channel', 'provider', 'status')->select(['channel', 'provider', 'status'])->selectRaw('COUNT(*) AS delivery_count')->selectRaw('MAX(created_at) AS last_created_at')->orderBy('channel')->orderBy('status'),
            'AUT-04' => DB::table('integration_sync_effects')->where('company_id', $companyId)->groupBy('connection_id', 'operation', 'status')->select(['connection_id', 'operation', 'status'])->selectRaw('COUNT(*) AS effect_count')->selectRaw('MAX(created_at) AS last_created_at')->orderBy('connection_id')->orderBy('operation')->orderBy('status'),
            'AUT-05' => DB::table('channel_problems')->where('company_id', $companyId)->where('status', 'open')->groupBy('connection_id', 'type')->select(['connection_id', 'type'])->selectRaw('COUNT(*) AS open_problem_count')->selectRaw('MIN(created_at) AS oldest_problem_at')->orderByDesc('open_problem_count'),
            'MGT-01' => DB::table('sales_invoices')->where('company_id', $companyId)->where('status', 'finalized')->groupBy('invoice_date', 'currency_code')->select(['invoice_date', 'currency_code'])->selectRaw('COUNT(*) AS invoice_count')->selectRaw('SUM(net_total) AS net_sales')->selectRaw('SUM(gross_total) AS gross_sales')->orderByDesc('invoice_date'),
            'MGT-02' => DB::table('account_transactions')->where('company_id', $companyId)->groupBy('posting_date', 'currency_code')->select(['posting_date', 'currency_code'])->selectRaw('SUM(CASE WHEN signed_amount > 0 THEN signed_amount ELSE 0 END) AS positive_postings')->selectRaw('ABS(SUM(CASE WHEN signed_amount < 0 THEN signed_amount ELSE 0 END)) AS settlements')->orderByDesc('posting_date'),
            'MGT-03' => DB::table('stock_balances')->where('company_id', $companyId)->selectRaw('COUNT(*) AS stock_positions')->selectRaw('COUNT(*) FILTER (WHERE available_quantity <= 0) AS critical_positions')->selectRaw('COALESCE(SUM(quantity), 0) AS physical_quantity')->selectRaw('COALESCE(SUM(available_quantity), 0) AS available_quantity')->selectRaw('COALESCE(SUM(inventory_value), 0) AS inventory_value'),
            'MGT-04' => DB::table('channel_problems')->where('company_id', $companyId)->where('status', 'open')->groupBy('type')->select(['type'])->selectRaw('COUNT(*) AS open_exception_count')->selectRaw('MIN(created_at) AS oldest_exception_at')->orderByDesc('open_exception_count'),
            'MGT-05' => DB::table('sales_invoice_lines as line')->join('sales_invoices as invoice', fn ($join) => $join->on('invoice.company_id', '=', 'line.company_id')->on('invoice.id', '=', 'line.sales_invoice_id'))->leftJoin('stock_movements as movement', function ($join): void { $join->on('movement.company_id', '=', 'line.company_id')->where('movement.source_type', '=', 'sales_invoice_line')->where('movement.effect_type', '=', 'stock.out')->where('movement.movement_type', '=', 'invoice_out')->whereRaw('movement.source_id = line.id::text'); })->where('line.company_id', $companyId)->where('invoice.status', 'finalized')->groupBy('invoice.currency_code')->select(['invoice.currency_code'])->selectRaw('SUM(line.net_total) AS recognized_revenue')->selectRaw('COALESCE(ABS(SUM(movement.value_delta)), 0) AS recognized_cost')->selectRaw('SUM(line.net_total) - COALESCE(ABS(SUM(movement.value_delta)), 0) AS recognized_margin')->orderBy('invoice.currency_code'),
            default => throw new InvalidArgumentException('Unknown report key: '.$reportKey),
        };
    }

    /** @return Collection<int, object> */
    public function run(string $reportKey, int $companyId, int $limit = 500): Collection
    {
        return $this->query($reportKey, $companyId)->limit(max(1, min(5000, $limit)))->get();
    }
}
