<?php

namespace App\Modules\Reports;

use Illuminate\Database\Query\Builder;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;

final class OperationalReportCatalog
{
    /** @return array<string, array{category:string,title:string,source:string}> */
    public function definitions(): array
    {
        return [
            'ACC-01' => ['category' => 'account_finance', 'title' => 'Cari Bakiye Listesi', 'source' => 'accounts + account_transactions'],
            'ACC-02' => ['category' => 'account_finance', 'title' => 'Cari Ekstre / Running Balance', 'source' => 'account_transactions'],
            'ACC-03' => ['category' => 'account_finance', 'title' => 'Vade / Aging Analizi', 'source' => 'accounts + account_transactions'],
            'ACC-04' => ['category' => 'account_finance', 'title' => 'Tahsilat ve Ödeme Özeti', 'source' => 'treasury_payments'],
            'ACC-05' => ['category' => 'account_finance', 'title' => 'Cari Risk / Exposure ve Limit Aşımları', 'source' => 'accounts + account_transactions'],
            'SAL-01' => ['category' => 'sales', 'title' => 'Satış Özeti — Gün/Ay/Dönem', 'source' => 'finalized sales_invoices'],
            'SAL-02' => ['category' => 'sales', 'title' => 'Müşteri Bazlı Satış', 'source' => 'finalized sales_invoices + accounts'],
            'SAL-03' => ['category' => 'sales', 'title' => 'Ürün/Kategori Bazlı Satış', 'source' => 'finalized sales_invoice_lines'],
            'SAL-04' => ['category' => 'sales', 'title' => 'Satış Siparişi Sevk/Fatura/Kalan Progress', 'source' => 'sales_orders + sales_order_line_progress_effects'],
            'SAL-05' => ['category' => 'sales', 'title' => 'Satış İade ve Net Satış Özeti', 'source' => 'sales_invoices + sales_returns'],
            'PUR-01' => ['category' => 'purchase', 'title' => 'Alış Özeti — Gün/Ay/Dönem', 'source' => 'supplier_invoices'],
            'PUR-02' => ['category' => 'purchase', 'title' => 'Tedarikçi Bazlı Alış', 'source' => 'supplier_invoices + accounts'],
            'PUR-03' => ['category' => 'purchase', 'title' => 'Ürün/Kategori Bazlı Alış', 'source' => 'supplier_invoice_lines'],
            'PUR-04' => ['category' => 'purchase', 'title' => 'Satınalma Siparişi Kabul/Fatura/Kalan Progress', 'source' => 'purchase_orders + purchase_order_line_progress_effects'],
            'PUR-05' => ['category' => 'purchase', 'title' => 'Mal Kabul Kalite / Bekleyen / Red Özeti', 'source' => 'goods_receipts + goods_receipt_lines'],
            'STK-01' => ['category' => 'stock_logistics', 'title' => 'Depo Bazlı Stok Bakiyesi ve Kullanılabilir', 'source' => 'stock_balances'],
            'STK-02' => ['category' => 'stock_logistics', 'title' => 'Stok Hareketleri', 'source' => 'stock_movements'],
            'STK-03' => ['category' => 'stock_logistics', 'title' => 'Rezervasyon / Kullanılabilir / Stok Eksikliği', 'source' => 'stock_balances + stock_reservations'],
            'STK-04' => ['category' => 'stock_logistics', 'title' => 'Depo Transferi / Yoldaki Stok', 'source' => 'warehouse_transfers + warehouse_transfer_lines'],
            'STK-05' => ['category' => 'stock_logistics', 'title' => 'Stok Sayım Farkları ve Stok Değeri', 'source' => 'stock_counts + stock_count_lines'],
            'PRD-01' => ['category' => 'production_subcontract', 'title' => 'Üretim Emri Durum / Progress', 'source' => 'production_orders'],
            'PRD-02' => ['category' => 'production_subcontract', 'title' => 'Malzeme Tüketimi', 'source' => 'production_order_materials'],
            'PRD-03' => ['category' => 'production_subcontract', 'title' => 'Mamul Girişi / Üretim Miktarı', 'source' => 'production_orders'],
            'PRD-04' => ['category' => 'production_subcontract', 'title' => 'Fire / Eksik / Sapma Özeti', 'source' => 'production_losses'],
            'SUB-01' => ['category' => 'production_subcontract', 'title' => 'Fason Gönderilen / Gelen / Kalan Custody', 'source' => 'subcontract_orders + subcontract_order_materials'],
            'IMP-01' => ['category' => 'imports', 'title' => 'Shipment / Konteyner Durum Özeti', 'source' => 'import_files + import_containers'],
            'IMP-02' => ['category' => 'imports', 'title' => 'Ürün–Konteyner–Koli Dağılımı', 'source' => 'import_items + import_containers'],
            'IMP-03' => ['category' => 'imports', 'title' => 'İthalat Maliyet Kalemleri ve Allocation Reconciliation', 'source' => 'import_landed_cost_batches + import_landed_cost_allocations'],
            'IMP-04' => ['category' => 'imports', 'title' => 'Ürün Bazlı Landed Cost', 'source' => 'import_landed_cost_allocations + import_receipt_links + import_items'],
            'IMP-05' => ['category' => 'imports', 'title' => 'Konteyner Hacim / Ağırlık / Yükleme Planı', 'source' => 'import_containers + import_items'],
            'COM-01' => ['category' => 'commerce', 'title' => 'Kanal Bazlı Sipariş / Ciro Özeti', 'source' => 'channel_order_inbox + sales_orders'],
            'COM-02' => ['category' => 'commerce', 'title' => 'Ürün Mapping ve Listing Durumu', 'source' => 'channel_product_mappings + channel_listing_states'],
            'COM-03' => ['category' => 'commerce', 'title' => 'Kanal Stok/Fiyat Sync ve Problem Özeti', 'source' => 'channel_listing_states + channel_problems'],
            'COM-04' => ['category' => 'commerce', 'title' => 'E-Ticaret İade / Soru / Operasyon Sorunları', 'source' => 'channel_return_events + channel_problems'],
            'COM-05' => ['category' => 'commerce', 'title' => 'Marketplace Clearing / Payout / Komisyon / Katkı Özeti', 'source' => 'channel_settlement_evidence'],
            'MGT-01' => ['category' => 'management', 'title' => 'Yönetim KPI Özeti', 'source' => 'finalized sales_invoices'],
            'MGT-02' => ['category' => 'management', 'title' => 'Satış–Alış Dönemsel Trend', 'source' => 'sales_invoices + supplier_invoices'],
            'MGT-03' => ['category' => 'management', 'title' => 'Stok Değeri / Hareketsiz Stok / Devir Göstergeleri', 'source' => 'stock_balances + stock_movements'],
            'MGT-04' => ['category' => 'management', 'title' => 'Cari Alacak–Borç / Nakit–Banka Pozisyon Özeti', 'source' => 'account_transactions + treasury_balances'],
            'MGT-05' => ['category' => 'management', 'title' => 'İstisna ve Kontrol Raporu', 'source' => 'channel_problems'],
        ];
    }

    /** @return list<string> */
    public function keys(): array
    {
        return array_keys($this->definitions());
    }

    public function query(string $reportKey, int $companyId): Builder
    {
        if (! isset($this->definitions()[$reportKey])) {
            throw new InvalidArgumentException('Unknown report key: '.$reportKey);
        }

        return match ($reportKey) {
            'ACC-01' => DB::table('accounts as account')->leftJoin('account_transactions as tx', fn ($join) => $join->on('tx.company_id', '=', 'account.company_id')->on('tx.account_id', '=', 'account.id'))->where('account.company_id', $companyId)->groupBy('account.id', 'account.code', 'account.legal_name', 'account.book_currency_code')->select(['account.code', 'account.legal_name', 'account.book_currency_code'])->selectRaw('COALESCE(SUM(tx.signed_amount), 0) AS balance')->orderBy('account.code'),
            'ACC-02' => DB::table('account_transactions as tx')->join('accounts as account', fn ($join) => $join->on('account.company_id', '=', 'tx.company_id')->on('account.id', '=', 'tx.account_id'))->where('tx.company_id', $companyId)->select(['tx.posting_date', 'tx.id', 'account.code as account_code', 'account.legal_name', 'tx.currency_code', 'tx.signed_amount', 'tx.source_type', 'tx.source_id', 'tx.effect_type', 'tx.memo'])->selectRaw('SUM(tx.signed_amount) OVER (PARTITION BY tx.account_id, tx.currency_code ORDER BY tx.posting_date, tx.id) AS running_balance')->orderByDesc('tx.posting_date')->orderByDesc('tx.id'),
            'ACC-03' => DB::table('accounts as account')->leftJoin('account_transactions as tx', fn ($join) => $join->on('tx.company_id', '=', 'account.company_id')->on('tx.account_id', '=', 'account.id'))->where('account.company_id', $companyId)->groupBy('account.id', 'account.code', 'account.legal_name', 'account.book_currency_code', 'account.due_days')->select(['account.code', 'account.legal_name', 'account.book_currency_code', 'account.due_days'])->selectRaw('COALESCE(SUM(tx.signed_amount), 0) AS outstanding')->selectRaw('COALESCE(SUM(CASE WHEN tx.signed_amount > 0 AND tx.posting_date + account.due_days < CURRENT_DATE THEN tx.signed_amount ELSE 0 END), 0) AS overdue_exposure')->orderByDesc('overdue_exposure'),
            'ACC-04' => DB::table('treasury_payments')->where('company_id', $companyId)->where('status', 'finalized')->groupBy('payment_date', 'currency_code', 'direction')->select(['payment_date', 'currency_code', 'direction'])->selectRaw('COUNT(*) AS payment_count')->selectRaw('SUM(amount) AS amount')->orderByDesc('payment_date'),
            'ACC-05' => DB::table('accounts as account')->leftJoin('account_transactions as tx', fn ($join) => $join->on('tx.company_id', '=', 'account.company_id')->on('tx.account_id', '=', 'account.id'))->where('account.company_id', $companyId)->groupBy('account.id', 'account.code', 'account.legal_name', 'account.book_currency_code', 'account.risk_limit')->select(['account.code', 'account.legal_name', 'account.book_currency_code', 'account.risk_limit'])->selectRaw('COALESCE(SUM(tx.signed_amount), 0) AS exposure')->selectRaw('GREATEST(COALESCE(SUM(tx.signed_amount), 0) - account.risk_limit, 0) AS limit_excess')->orderByDesc('limit_excess'),
            'SAL-01' => DB::table('sales_invoices')->where('company_id', $companyId)->where('status', 'finalized')->groupBy('invoice_date', 'currency_code')->select(['invoice_date', 'currency_code'])->selectRaw('COUNT(*) AS invoice_count')->selectRaw('SUM(net_total) AS net_sales')->selectRaw('SUM(gross_total) AS gross_sales')->orderByDesc('invoice_date'),
            'SAL-02' => DB::table('sales_invoices as invoice')->join('accounts as account', fn ($join) => $join->on('account.company_id', '=', 'invoice.company_id')->on('account.id', '=', 'invoice.account_id'))->where('invoice.company_id', $companyId)->where('invoice.status', 'finalized')->groupBy('account.id', 'account.code', 'account.legal_name', 'invoice.currency_code')->select(['account.code', 'account.legal_name', 'invoice.currency_code'])->selectRaw('COUNT(*) AS invoice_count')->selectRaw('SUM(invoice.net_total) AS net_sales')->selectRaw('SUM(invoice.gross_total) AS gross_sales')->orderByDesc('gross_sales'),
            'SAL-03' => DB::table('sales_invoice_lines as line')->join('sales_invoices as invoice', fn ($join) => $join->on('invoice.company_id', '=', 'line.company_id')->on('invoice.id', '=', 'line.sales_invoice_id'))->where('line.company_id', $companyId)->where('invoice.status', 'finalized')->groupBy('line.product_id', 'line.product_code', 'line.product_name', 'invoice.currency_code')->select(['line.product_id', 'line.product_code', 'line.product_name', 'invoice.currency_code'])->selectRaw('SUM(line.quantity) AS quantity')->selectRaw('SUM(line.net_total) AS net_sales')->selectRaw('SUM(line.gross_total) AS gross_sales')->orderByDesc('net_sales'),
            'SAL-04' => DB::table('sales_orders as orders')->leftJoin('sales_order_lines as line', fn ($join) => $join->on('line.company_id', '=', 'orders.company_id')->on('line.sales_order_id', '=', 'orders.id'))->leftJoin('sales_order_line_progress_effects as progress', fn ($join) => $join->on('progress.company_id', '=', 'line.company_id')->on('progress.sales_order_id', '=', 'orders.id')->on('progress.sales_order_line_id', '=', 'line.id'))->where('orders.company_id', $companyId)->groupBy('orders.id', 'orders.number', 'orders.order_date', 'orders.status', 'orders.currency_code', 'orders.gross_total')->select(['orders.number', 'orders.order_date', 'orders.status', 'orders.currency_code', 'orders.gross_total'])->selectRaw('COALESCE(SUM(line.quantity), 0) AS ordered_quantity')->selectRaw("COALESCE(SUM(CASE WHEN progress.progress_type = 'dispatched' THEN progress.quantity_delta ELSE 0 END), 0) AS dispatched_quantity")->selectRaw("COALESCE(SUM(CASE WHEN progress.progress_type = 'invoiced' THEN progress.quantity_delta ELSE 0 END), 0) AS invoiced_quantity")->orderByDesc('orders.order_date'),
            'SAL-05' => DB::table('sales_invoices as invoice')->leftJoin('sales_returns as returns', fn ($join) => $join->on('returns.company_id', '=', 'invoice.company_id')->on('returns.sales_invoice_id', '=', 'invoice.id')->where('returns.status', '=', 'completed'))->where('invoice.company_id', $companyId)->where('invoice.status', 'finalized')->groupBy('invoice.invoice_date', 'invoice.currency_code')->select(['invoice.invoice_date', 'invoice.currency_code'])->selectRaw('SUM(invoice.gross_total) AS gross_sales')->selectRaw('COALESCE(SUM(returns.credited_gross_total), 0) AS returns')->selectRaw('SUM(invoice.gross_total) - COALESCE(SUM(returns.credited_gross_total), 0) AS net_after_returns')->orderByDesc('invoice.invoice_date'),
            'PUR-01' => DB::table('supplier_invoices')->where('company_id', $companyId)->where('status', 'finalized')->groupBy('invoice_date', 'currency_code')->select(['invoice_date', 'currency_code'])->selectRaw('COUNT(*) AS invoice_count')->selectRaw('SUM(net_total) AS net_purchase')->selectRaw('SUM(gross_total) AS gross_purchase')->orderByDesc('invoice_date'),
            'PUR-02' => DB::table('supplier_invoices as invoice')->join('accounts as account', fn ($join) => $join->on('account.company_id', '=', 'invoice.company_id')->on('account.id', '=', 'invoice.account_id'))->where('invoice.company_id', $companyId)->where('invoice.status', 'finalized')->groupBy('account.id', 'account.code', 'account.legal_name', 'invoice.currency_code')->select(['account.code', 'account.legal_name', 'invoice.currency_code'])->selectRaw('COUNT(*) AS invoice_count')->selectRaw('SUM(invoice.net_total) AS net_purchase')->selectRaw('SUM(invoice.gross_total) AS gross_purchase')->orderByDesc('gross_purchase'),
            'PUR-03' => DB::table('supplier_invoice_lines as line')->join('supplier_invoices as invoice', fn ($join) => $join->on('invoice.company_id', '=', 'line.company_id')->on('invoice.id', '=', 'line.supplier_invoice_id'))->where('line.company_id', $companyId)->where('invoice.status', 'finalized')->groupBy('line.product_id', 'line.product_code', 'line.product_name', 'invoice.currency_code')->select(['line.product_id', 'line.product_code', 'line.product_name', 'invoice.currency_code'])->selectRaw('SUM(line.quantity) AS quantity')->selectRaw('SUM(line.net_total) AS net_purchase')->selectRaw('SUM(line.gross_total) AS gross_purchase')->orderByDesc('net_purchase'),
            'PUR-04' => DB::table('purchase_orders as orders')->leftJoin('purchase_order_lines as line', fn ($join) => $join->on('line.company_id', '=', 'orders.company_id')->on('line.purchase_order_id', '=', 'orders.id'))->leftJoin('purchase_order_line_progress_effects as progress', fn ($join) => $join->on('progress.company_id', '=', 'line.company_id')->on('progress.purchase_order_id', '=', 'orders.id')->on('progress.purchase_order_line_id', '=', 'line.id'))->where('orders.company_id', $companyId)->groupBy('orders.id', 'orders.number', 'orders.order_date', 'orders.status', 'orders.currency_code', 'orders.gross_total')->select(['orders.number', 'orders.order_date', 'orders.status', 'orders.currency_code', 'orders.gross_total'])->selectRaw('COALESCE(SUM(line.quantity), 0) AS ordered_quantity')->selectRaw("COALESCE(SUM(CASE WHEN progress.progress_type = 'received' THEN progress.quantity_delta ELSE 0 END), 0) AS received_quantity")->selectRaw("COALESCE(SUM(CASE WHEN progress.progress_type = 'invoiced' THEN progress.quantity_delta ELSE 0 END), 0) AS invoiced_quantity")->orderByDesc('orders.order_date'),
            'PUR-05' => DB::table('goods_receipt_lines as line')->join('goods_receipts as receipt', fn ($join) => $join->on('receipt.company_id', '=', 'line.company_id')->on('receipt.id', '=', 'line.goods_receipt_id'))->where('line.company_id', $companyId)->groupBy('receipt.receipt_date', 'line.product_id', 'line.product_code', 'line.product_name')->select(['receipt.receipt_date', 'line.product_id', 'line.product_code', 'line.product_name'])->selectRaw('SUM(line.received_quantity) AS received_quantity')->selectRaw('SUM(line.accepted_quantity) AS accepted_quantity')->selectRaw('SUM(line.pending_quantity) AS pending_quantity')->selectRaw('SUM(line.rejected_quantity) AS rejected_quantity')->orderByDesc('receipt.receipt_date'),
            'STK-01' => DB::table('stock_balances as balance')->join('products as product', fn ($join) => $join->on('product.company_id', '=', 'balance.company_id')->on('product.id', '=', 'balance.product_id'))->join('warehouses as warehouse', fn ($join) => $join->on('warehouse.company_id', '=', 'balance.company_id')->on('warehouse.id', '=', 'balance.warehouse_id'))->where('balance.company_id', $companyId)->select(['product.code as product_code', 'product.name as product_name', 'warehouse.code as warehouse_code', 'balance.quantity', 'balance.reserved_quantity', 'balance.blocked_quantity', 'balance.available_quantity', 'balance.average_unit_cost', 'balance.inventory_value'])->orderBy('product.code'),
            'STK-02' => DB::table('stock_movements as movement')->join('products as product', fn ($join) => $join->on('product.company_id', '=', 'movement.company_id')->on('product.id', '=', 'movement.product_id'))->where('movement.company_id', $companyId)->select(['movement.occurred_at', 'product.code as product_code', 'movement.movement_type', 'movement.quantity_delta', 'movement.unit_cost', 'movement.value_delta', 'movement.source_type', 'movement.source_id', 'movement.effect_type'])->orderByDesc('movement.occurred_at')->orderByDesc('movement.id'),
            'STK-03' => DB::table('stock_balances as balance')->join('products as product', fn ($join) => $join->on('product.company_id', '=', 'balance.company_id')->on('product.id', '=', 'balance.product_id'))->where('balance.company_id', $companyId)->select(['product.code as product_code', 'product.name as product_name', 'balance.warehouse_id', 'balance.location_id', 'balance.quantity', 'balance.reserved_quantity', 'balance.blocked_quantity', 'balance.available_quantity'])->selectRaw('CASE WHEN balance.available_quantity <= 0 THEN true ELSE false END AS shortage')->orderBy('product.code'),
            'STK-04' => DB::table('warehouse_transfers as transfer')->leftJoin('warehouse_transfer_lines as line', fn ($join) => $join->on('line.company_id', '=', 'transfer.company_id')->on('line.transfer_id', '=', 'transfer.id'))->where('transfer.company_id', $companyId)->groupBy('transfer.id', 'transfer.status', 'transfer.source_warehouse_id', 'transfer.destination_warehouse_id', 'transfer.issued_at', 'transfer.completed_at')->select(['transfer.status', 'transfer.source_warehouse_id', 'transfer.destination_warehouse_id', 'transfer.issued_at', 'transfer.completed_at'])->selectRaw('COALESCE(SUM(line.in_transit_quantity), 0) AS in_transit_quantity')->selectRaw('COALESCE(SUM(line.in_transit_value), 0) AS in_transit_value')->orderByDesc('transfer.issued_at'),
            'STK-05' => DB::table('stock_count_lines as line')->join('stock_counts as counts', fn ($join) => $join->on('counts.company_id', '=', 'line.company_id')->on('counts.id', '=', 'line.stock_count_id'))->join('products as product', fn ($join) => $join->on('product.company_id', '=', 'line.company_id')->on('product.id', '=', 'line.product_id'))->where('line.company_id', $companyId)->select(['counts.started_at', 'counts.status', 'product.code as product_code', 'line.expected_quantity', 'line.expected_value', 'line.counted_quantity', 'line.variance_quantity'])->orderByDesc('counts.started_at'),
            'PRD-01' => DB::table('production_orders')->where('company_id', $companyId)->select(['order_no', 'status', 'product_id', 'planned_quantity', 'output_quantity', 'material_issued_at', 'received_at', 'completed_at'])->orderByDesc('id'),
            'PRD-02' => DB::table('production_order_materials as material')->join('production_orders as orders', fn ($join) => $join->on('orders.company_id', '=', 'material.company_id')->on('orders.id', '=', 'material.production_order_id'))->where('material.company_id', $companyId)->select(['orders.order_no', 'material.product_id', 'material.required_quantity', 'material.issued_quantity', 'material.issued_value'])->orderByDesc('orders.id'),
            'PRD-03' => DB::table('production_orders')->where('company_id', $companyId)->select(['order_no', 'status', 'planned_quantity', 'output_quantity', 'output_unit_cost', 'output_value', 'received_at'])->selectRaw('CASE WHEN planned_quantity = 0 THEN 0 ELSE output_quantity / planned_quantity END AS output_efficiency')->orderByDesc('id'),
            'PRD-04' => DB::table('production_losses as loss')->join('production_orders as orders', fn ($join) => $join->on('orders.company_id', '=', 'loss.company_id')->on('orders.id', '=', 'loss.production_order_id'))->where('loss.company_id', $companyId)->groupBy('orders.order_no', 'loss.loss_type')->select(['orders.order_no', 'loss.loss_type'])->selectRaw('SUM(loss.quantity) AS quantity')->selectRaw('SUM(loss.carrying_value) AS carrying_value')->orderBy('orders.order_no'),
            'SUB-01' => DB::table('subcontract_order_materials as material')->join('subcontract_orders as orders', fn ($join) => $join->on('orders.company_id', '=', 'material.company_id')->on('orders.id', '=', 'material.subcontract_order_id'))->where('material.company_id', $companyId)->select(['orders.order_no', 'orders.status', 'material.product_id', 'material.sent_quantity', 'material.consumed_quantity', 'material.loss_quantity'])->selectRaw('material.sent_quantity - material.consumed_quantity - material.loss_quantity AS custody_quantity')->orderByDesc('orders.id'),
            'IMP-01' => DB::table('import_files as file')->leftJoin('import_containers as container', fn ($join) => $join->on('container.company_id', '=', 'file.company_id')->on('container.import_file_id', '=', 'file.id'))->where('file.company_id', $companyId)->groupBy('file.id', 'file.number', 'file.status', 'file.departure_date', 'file.expected_arrival_date', 'file.arrival_date')->select(['file.number', 'file.status', 'file.departure_date', 'file.expected_arrival_date', 'file.arrival_date'])->selectRaw('COUNT(container.id) AS container_count')->orderByDesc('file.id'),
            'IMP-02' => DB::table('import_items as item')->leftJoin('import_containers as container', fn ($join) => $join->on('container.company_id', '=', 'item.company_id')->on('container.id', '=', 'item.import_container_id'))->where('item.company_id', $companyId)->groupBy('item.product_id', 'container.container_no')->select(['item.product_id', 'container.container_no'])->selectRaw('SUM(item.quantity) AS quantity')->selectRaw('SUM(item.package_count) AS package_count')->selectRaw('SUM(item.gross_weight_kg) AS gross_weight_kg')->selectRaw('SUM(item.volume_m3) AS volume_m3')->orderBy('container.container_no'),
            'IMP-03' => DB::table('import_landed_cost_batches as batch')->leftJoin('import_landed_cost_allocations as allocation', fn ($join) => $join->on('allocation.company_id', '=', 'batch.company_id')->on('allocation.landed_cost_batch_id', '=', 'batch.id'))->where('batch.company_id', $companyId)->groupBy('batch.id', 'batch.import_file_id', 'batch.allocation_basis', 'batch.expense_total', 'batch.currency_code', 'batch.posted_at')->select(['batch.import_file_id', 'batch.allocation_basis', 'batch.expense_total', 'batch.currency_code', 'batch.posted_at'])->selectRaw('COALESCE(SUM(allocation.allocated_amount), 0) AS allocated_total')->selectRaw('batch.expense_total - COALESCE(SUM(allocation.allocated_amount), 0) AS reconciliation_difference')->orderByDesc('batch.posted_at'),
            'IMP-04' => DB::table('import_landed_cost_allocations as allocation')->join('import_receipt_links as link', fn ($join) => $join->on('link.company_id', '=', 'allocation.company_id')->on('link.id', '=', 'allocation.import_receipt_link_id'))->join('import_items as item', fn ($join) => $join->on('item.company_id', '=', 'link.company_id')->on('item.id', '=', 'link.import_item_id'))->where('allocation.company_id', $companyId)->groupBy('item.product_id')->select(['item.product_id'])->selectRaw('SUM(allocation.allocated_amount) AS landed_cost')->selectRaw('SUM(link.linked_quantity) AS linked_quantity')->orderByDesc('landed_cost'),
            'IMP-05' => DB::table('import_containers as container')->leftJoin('import_items as item', fn ($join) => $join->on('item.company_id', '=', 'container.company_id')->on('item.import_container_id', '=', 'container.id'))->where('container.company_id', $companyId)->groupBy('container.id', 'container.container_no', 'container.container_type', 'container.max_weight_kg', 'container.max_volume_m3')->select(['container.container_no', 'container.container_type', 'container.max_weight_kg', 'container.max_volume_m3'])->selectRaw('COALESCE(SUM(item.package_count), 0) AS package_count')->selectRaw('COALESCE(SUM(item.gross_weight_kg), 0) AS gross_weight_kg')->selectRaw('COALESCE(SUM(item.volume_m3), 0) AS volume_m3')->orderBy('container.container_no'),
            'COM-01' => DB::table('channel_order_inbox as inbox')->leftJoin('sales_orders as orders', fn ($join) => $join->on('orders.company_id', '=', 'inbox.company_id')->on('orders.id', '=', 'inbox.sales_order_id'))->where('inbox.company_id', $companyId)->groupBy('inbox.connection_id', 'inbox.status', 'orders.currency_code')->select(['inbox.connection_id', 'inbox.status', 'orders.currency_code'])->selectRaw('COUNT(*) AS order_count')->selectRaw('COALESCE(SUM(orders.gross_total), 0) AS gross_sales')->selectRaw('MAX(inbox.received_at) AS last_received_at')->orderBy('inbox.connection_id'),
            'COM-02' => DB::table('channel_product_mappings as mapping')->leftJoin('channel_listing_states as listing', fn ($join) => $join->on('listing.company_id', '=', 'mapping.company_id')->on('listing.mapping_id', '=', 'mapping.id'))->where('mapping.company_id', $companyId)->select(['mapping.connection_id', 'mapping.product_id', 'mapping.external_product_id', 'mapping.external_variant_id', 'mapping.external_sku', 'mapping.status as mapping_status', 'listing.status as listing_status', 'listing.desired_version', 'listing.published_version'])->orderBy('mapping.connection_id')->orderBy('mapping.id'),
            'COM-03' => DB::table('channel_listing_states as listing')->where('listing.company_id', $companyId)->select(['listing.connection_id', 'listing.mapping_id', 'listing.status', 'listing.desired_stock', 'listing.published_stock', 'listing.desired_price', 'listing.published_price', 'listing.desired_version', 'listing.published_version', 'listing.last_error'])->orderBy('listing.connection_id')->orderBy('listing.id'),
            'COM-04' => DB::table('channel_return_events as returns')->where('returns.company_id', $companyId)->groupBy('returns.connection_id', 'returns.status')->select(['returns.connection_id', 'returns.status'])->selectRaw('COUNT(*) AS return_event_count')->selectRaw('MAX(returns.updated_at) AS last_updated_at')->orderBy('returns.connection_id'),
            'COM-05' => DB::table('channel_settlement_evidence')->where('company_id', $companyId)->groupBy('connection_id', 'currency_code', 'clearing_account_id', 'status')->select(['connection_id', 'currency_code', 'clearing_account_id', 'status'])->selectRaw('SUM(gross_amount) AS gross_amount')->selectRaw('SUM(fee_amount) AS fee_amount')->selectRaw('SUM(net_amount) AS net_amount')->selectRaw("SUM(CASE WHEN status = 'handed_off' THEN net_amount ELSE 0 END) AS handed_off_net")->orderBy('connection_id'),
            'MGT-01' => DB::table('sales_invoices')->where('company_id', $companyId)->where('status', 'finalized')->selectRaw('COUNT(*) AS invoice_count')->selectRaw('COALESCE(SUM(net_total), 0) AS net_sales')->selectRaw('COALESCE(SUM(gross_total), 0) AS gross_sales'),
            'MGT-02' => DB::table('sales_invoices')->where('company_id', $companyId)->where('status', 'finalized')->groupBy('invoice_date', 'currency_code')->select(['invoice_date', 'currency_code'])->selectRaw('SUM(net_total) AS sales_net')->selectRaw('SUM(gross_total) AS sales_gross')->orderByDesc('invoice_date'),
            'MGT-03' => DB::table('stock_balances')->where('company_id', $companyId)->selectRaw('COUNT(*) AS stock_positions')->selectRaw('COUNT(*) FILTER (WHERE available_quantity <= 0) AS critical_positions')->selectRaw('COALESCE(SUM(quantity), 0) AS physical_quantity')->selectRaw('COALESCE(SUM(available_quantity), 0) AS available_quantity')->selectRaw('COALESCE(SUM(inventory_value), 0) AS inventory_value'),
            'MGT-04' => DB::table('treasury_balances as balance')->join('treasury_accounts as account', fn ($join) => $join->on('account.company_id', '=', 'balance.company_id')->on('account.id', '=', 'balance.treasury_account_id'))->where('balance.company_id', $companyId)->groupBy('account.type', 'account.currency_code')->select(['account.type', 'account.currency_code'])->selectRaw('SUM(balance.balance) AS balance')->orderBy('account.type'),
            'MGT-05' => DB::table('channel_problems')->where('company_id', $companyId)->where('status', 'open')->groupBy('type')->select(['type'])->selectRaw('COUNT(*) AS open_exception_count')->selectRaw('MIN(created_at) AS oldest_exception_at')->orderByDesc('open_exception_count'),
            default => throw new InvalidArgumentException('Unknown report key: '.$reportKey),
        };
    }

    /** @return Collection<int, \stdClass> */
    public function run(string $reportKey, int $companyId, int $limit = 500): Collection
    {
        return $this->query($reportKey, $companyId)->limit(max(1, min(5000, $limit)))->get();
    }
}
